{"uuid": "5fdb3864-8715-4f12-856d-3051ce8579fe", "children": ["f10aa3d6-8641-4595-8f82-e993693053db"], "befores": [{"name": "xunit_setup_class_fixture_TestContact", "status": "passed", "start": 1646062822134, "stop": 1646062822135}], "afters": [{"name": "xunit_setup_class_fixture_TestContact::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'NoneType' object has no attribute 'quit'\n", "trace": "  File \"C:\\Users\\91373\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\91373\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 941, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\91373\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\python.py\", line 815, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"C:\\Users\\91373\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\python.py\", line 739, in _call_with_optional_argument\n    func(arg)\n  File \"C:\\python-system\\iSelenium_Python1\\app\\testcase\\test_contact.py\", line 17, in teardown_class\n    self.app.stop()\n  File \"C:\\python-system\\iSelenium_Python1\\app\\page\\app.py\", line 54, in stop\n    self.driver.quit()\n"}, "start": 1646062822157, "stop": 1646062822160}], "start": 1646062822134, "stop": 1646062822160}